### ISSUE TITLE
MySQL connection error

### ISSUE THREAD

**Issue by tnakao62** [sennbei/re_shiftmaker#2]
laravel が MySQL コンテナを認識できていない。
laravel からデータベースにテーブル作成コマンドを送ると、接続が失敗した。

re_shiftmaker/laravel $ php artisan migrate
![default](https://user-images.githubusercontent.com/31564802/31305996-5e86b612-ab81-11e7-99e4-ad13479ec00e.JPG)

migrate はlaravel がサポートしているテーブル定義の更新メソッド
以下のディレクトリで更新内容を定義できる
re_shiftmaker/laravel/database/migrations

**Comment by sennbei** [comment]
migrateはコンテナ上で行う。
また、DB_HOSTにlocal IPが投入されていたため、mysqlのコンテナを参照に行っていなかった
.envにて
``` .env
DB_HOST=db
```
とし、
```
$ docker-compose up -d
$ docker-compose` run laravel php artisan migrate
```
で作成できた。

**Comment by sennbei** [comment]
本件、.envの修正というよりはdatabase.phpの修正の方が正しそう？
```
'host' => env('DB_HOST', '127.0.0.1')
```
から
```
'host' => env('DB_HOST', 'db')
```

**Comment by sennbei** [comment]
下記Commitにて解消。
1acf4caf319c1180ca37deca30a35c751e298357
