### ISSUE TITLE
ERROR apache connect

### ISSUE THREAD

**Issue by tnakao62** [sennbei/re_shiftmaker#5]
develop branch
最新コミットでコンテナの再ビルド後、apache上のアプリケーションにアクセスできない

laravel のログには何も出力されていないので、おそらくapache側の問題
apacheのログの場所がわからないので捜査できず
同様の現象は起こりますか？apacheログの場所はわかりますか？
![default](https://user-images.githubusercontent.com/31564802/31581736-d31f3ffe-b1ac-11e7-829a-e4068f6ee501.JPG)

再ビルドの直前によくわからないパーミッションの問題が出たので再ビルド実施
どうやらキャッシュのパーミッションが無いようなメッセージだった
パーミッションの問題自体はアプリケーションの変更によるものだと思う

**Comment by tnakao62** [comment]
パーミッションエラー発生時のアプリケーション側のコードはコメントアウト中
他のＵＲＬ（localhost/testとか）にも同じエラーが表示
php artisan migrate は成功し、mysql でテーブルが正しく作成されていることを確認

**Comment by sennbei** [comment]
すいませんfront_appのポート変えたの連絡忘れてました...
8000番でアクセスしてみてください

**Comment by tnakao62** [comment]
ありがとう。解決
